[package]
name = "payments_api"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
chrono = "0.4.41"
diesel = { version = "2.2.12", features = ["postgres", "r2d2"] }
r2d2 = "0.8.10"
redis = "0.32.4"
serde = { version = "1.0.219", features = ["derive"] }
async-trait = "0.1.88"
